### ISSUE TITLE
short user leads to glitches for user menu entries

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#1080] opened 2017-09-29 12:18 UTC
![sep-29-2017 14-15-05](https://user-images.githubusercontent.com/683773/31015505-cb3005b4-a520-11e7-8940-cf3bba9e29de.gif)

The panel seems to us a min-width to small for the displayed contend if a short user name was chosen. Additionally overflow: hidden should be used or text-overflow: elipsis.

Currently the "UI" breaks to the next line causing a strange looking icon.

**Comment by mstruebing** [comment] 2017-10-04 07:45
I can't reproduce it, for me it seems correct even for a shorter name as Foo Bar. Are you sure you are using the current master? Maybe it has something to do with the font? We recently switched to Open Sans which maybe is a bit smaller?

**Comment by johannessteu** [comment] 2017-10-13 12:45
Can't reproduce as well

**Comment by mstruebing** [comment] 2017-10-19 13:06
Closing this for now as we both can't reproduce it. If anybody can reproduce feel free to open it again

**Closed by mstruebing** 2017-10-19 13:07 UTC
Labels: Bug, Good first issue, Hacktoberfest, to validate / retest
