### ISSUE TITLE
PreviewButton always opens a new browser tab

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-ui#1880] opened 2018-05-18 09:35 UTC
### Description

With https://github.com/neos/neos-development-collection/commit/cbb7f9dc619decd17f06304804157f9646c4314b we told Neos to always show the preview in the same browser tab.
This behavior seems to be lost with the React UI: Every click on the previewButton opens a new tab.

### Steps to Reproduce

1. Hit the preview link: 
![image](https://user-images.githubusercontent.com/307571/40227625-4f5942aa-5a8f-11e8-9bb5-cd7eae499c3c.png)

#### Expected behavior

The first time a new browser tab should be opened to display the content.
Successive clicks should re-focus the previously opened preview tab and reload the content.

#### Actual behavior

Every click opens a new browser tab

### Affected Versions

UI: All up to `v1.1.0`

**Comment by dimaip** [comment] 2018-05-18 10:58
Duplicate of #1749

**Closed by dimaip** 2018-05-18 10:58 UTC
Labels: Bug, Editor Ui Regression, UI & UX

**Comment by bwaidelich** [comment] 2018-05-18 11:03
Doh, I searched for "browser tab" but didn't find the issue for some reason. Thx
