### ISSUE TITLE
Error when removing a document with child documents

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1345] opened 2017-11-24 14:36 UTC
When I try to remove a document having sub dcoments, I get an error on publish:

![image](https://user-images.githubusercontent.com/642226/33214589-d4642484-d12c-11e7-9dc4-253f4b6f4075.png)

Without log message.

And when I hit publish again, the error changes: 
![image](https://user-images.githubusercontent.com/642226/33214609-e8a30f8c-d12c-11e7-9879-19ac412ea690.png)

Stack Trace:

```
Exception in line 804 of /var/www/releases/20171124140829/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Neos_Neos_Ui_Controller_BackendServiceController.php: Call to a member function isRemoved() on null

35 Neos\Neos\Ui\Controller\BackendServiceController_Original::discardAction(array|57|)
34 Neos\Neos\Ui\Controller\BackendServiceController::discardAction(array|57|)
33 call_user_func_array(array|2|, array|1|)
32 Neos\Neos\Ui\Controller\BackendServiceController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
31 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
30 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
29 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
28 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
27 Neos\Neos\Ui\Controller\BackendServiceController::discardAction(array|57|)
26 call_user_func_array(array|2|, array|1|)
25 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
24 Neos\Neos\Ui\Controller\BackendServiceController::callActionMethod()
23 call_user_func_array(array|2|, array|0|)
22 Neos\Neos\Ui\Controller\BackendServiceController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
21 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
20 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
19 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
18 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
17 Neos\Neos\Ui\Controller\BackendServiceController::callActionMethod()
16 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Http\Response)
15 Neos\Neos\Ui\Controller\BackendServiceController::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Http\Response)
14 call_user_func_array(array|2|, array|2|)
13 Neos\Neos\Ui\Controller\BackendServiceController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
12 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
11 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
10 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
9 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
8 Neos\Neos\Ui\Controller\BackendServiceController::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Http\Response)
7 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Http\Response)
6 Neos\Flow\Mvc\Dispatcher_Original::dispatch(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Http\Response)
5 Neos\Flow\Mvc\DispatchComponent_Original::handle(Neos\Flow\Http\Component\ComponentContext)
4 Neos\Flow\Http\Component\ComponentChain_Original::handle(Neos\Flow\Http\Component\ComponentContext)
3 Neos\Flow\Http\Component\ComponentChain_Original::handle(Neos\Flow\Http\Component\ComponentContext)
2 Neos\Flow\Http\RequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()
```

**Comment by dimaip** [comment] 2017-11-24 16:28
I can't reliably reproduce it, even though I did see this error a few times. Can you?

**Comment by mstruebing** [comment] 2017-12-19 11:16
I can't reproduce it either.
I close this for now, if this issue still occurs feel free to open again.

**Closed** 2017-12-19 11:16 UTC
Labels: Bug
