### ISSUE TITLE
Integrate the editors also in the creating dialog

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#1034] opened 2017-09-27 06:50 UTC
At the moment, not all available editors (e.g. DateTime) are available in the creationDialog. In order to make advanced use of https://github.com/Flowpack/Flowpack.NodeTemplates/, it is important to have all of them in the dialog.

**Comment by jonnitto** [comment] 2017-09-27 11:38
In the properties definition, you need to set the editor inside of the inspector, in the creatinDialog not. The editor are available. The editorOptions aren't working, but this is another issue…

**Comment by dimaip** [comment] 2017-09-27 12:47
Hmm actually I'm sure some advanced editors like Image editor won't work, so re-opening.

**Comment by dimaip** [comment] 2017-09-27 12:47
Or does image editor work for you?

**Comment by jonnitto** [comment] 2017-09-28 10:48
I‘ll test it

**Comment by jonnitto** [comment] 2017-10-10 08:36
Yes, you are right. The image editor doesn't work correctly.

**Comment by bwaidelich** [comment] 2018-01-08 09:31
I can confirm, that the `ImageEditor` won't work from the `creationDialog`: The `MediaBrowser` won't be shown – this is probably a challenge to achieve UX wise..

**Comment by bweinzierl** [comment] 2019-06-14 17:15
I stumbled across this problem today while using the mentioned Flowpack.NodeTemplates. In my case the ImageEditor and the AssetEditor both cannot open the MediaBrowser. This would be a much needed Feature to greatly improve the backend user experience.

**Comment by bwaidelich** [comment] 2019-11-22 10:20
Since we're planning to integrate the "creation dialog properties" feature into Neos 5.1 (see https://discuss.neos.io/t/rfc-allow-node-properties-to-appear-in-the-creation-dialog/3687) this issue will get more relevance. Maybe we can come up with an intermediate solution like a custom editor with limited browsing functionality?

**Comment by bwaidelich** [comment] 2019-11-28 10:06
FYI: Currently those are the core editors that don't (completely) work in Creation Dialogs due to the secondary view:
* `Neos.Neos/Inspector/Editors/ImageEditor`
* `Neos.Neos/Inspector/Editors/AssetEditor`
* `Neos.Neos/Inspector/Editors/RichTextEditor`
* `Neos.Neos/Inspector/Editors/CodeEditor`

We briefly discussed this in our weekly team meeting yesterday. One (probably simpler but not so UX-y way) might be to open the original modal _on top_ of the Creation Dialog modal.
Alternatively we could maybe expand the secondary view like we currently do with DateTime properties:

![image](https://user-images.githubusercontent.com/307571/69796798-ef109d00-11ce-11ea-8428-c58cfab9ecf4.png)

![image](https://user-images.githubusercontent.com/307571/69796814-f33cba80-11ce-11ea-999b-f51986ca8f8c.png)

I have no clue how much work that would be.. For now I'll disable those editors for https://github.com/neos/neos-development-collection/issues/2173

**Comment by Sebobo** [comment] 2020-07-03 20:29
This is also an interesting topic for the new media ui. 
Maybe embedding the secondary inspector is the best option.
I anyway wanted to make the media selector fully responsive.

**Comment by bwaidelich** [comment] 2021-03-17 08:45
With #2870 merged this can be closed, right?

**Closed** 2021-03-17 09:35 UTC
Labels: Enhancement, Reminder, UI & UX
