### ISSUE TITLE
Bug: Text overflow in node deletion modal dialog

### ISSUE THREAD

**Issue by pKallert** [neos/neos-ui#3295] opened 2022-12-13 14:47 UTC
### Description
When deleting a node with a long content the text overflows the confirmation popup

### Steps to Reproduce

1. Create a new text element, for example of type 'Neos.Demo:Content.Text'
2. Add content "DingedingeDingedingeDingedingeDingedinge" to text element
3. Delete new text element 

#### Expected behavior
A popup is shown for confirmation. Text stays inside the popup

#### Actual behavior
The text overflows the popup and in the popup content a scrollbar shows up: 
![Bildschirmfoto 2022-12-13 um 15 43 22](https://user-images.githubusercontent.com/91674611/207364942-e8ccdb08-25a4-438e-ab53-6a2e73afc2a3.png)

**Comment by crydotsnake** [comment] 2022-12-13 17:00
Is this a duplicate of #3295 ?

**Closed as completed** 2022-12-14 08:38 UTC
