### ISSUE TITLE
Newly created pages in the document tree disappear/are not displayed

### ISSUE THREAD

**Issue by olimination** [neos/neos-ui#3248] opened 2022-11-10 05:55 UTC
### Description

With the "[Code Q Neos Skeleton](https://github.com/code-q-web-factory/Neos-Skeleton/tree/98ef442fc8bebc69638abedb2e479fb72220fa9d)" created pages disappear in the document tree.

A first analysis showed that the Cache config of the [Footer Fusion component](https://github.com/code-q-web-factory/Neos-Skeleton/blob/master/DistributionPackages/CodeQ.Site/Resources/Private/Fusion/Component/Footer/Footer.fusion) seems to produce the issue, see more [details here](https://discuss.neos.io/t/beginner-question-content-tree-problems-in-ui/5843/11?u=olibur).

See Screencast here: https://vimeo.com/681370643 (created by maxodoble see also discussion [post here](https://discuss.neos.io/t/beginner-question-content-tree-problems-in-ui/5843/5)).

There is also a bug report in the Code Q repository [here](https://github.com/code-q-web-factory/Neos-Skeleton/issues/27).

More details also in this [discussion thread](https://discuss.neos.io/t/beginner-question-content-tree-problems-in-ui/5843).

### Steps to Reproduce

1. Install Neos with the [Code Q Neos Skeleton](https://github.com/code-q-web-factory/Neos-Skeleton/blob/master/docs/GETTING_STARTED.md) currently latest commit `98ef442fc8bebc69638abedb2e479fb72220fa9d`
2. Open Neos Admin Backend
3. Create few pages below Homepage
4. Created pages disappear again

#### Expected behavior

The created pages should be displayed.

#### Actual behavior

Screencast: https://vimeo.com/681370643

### Affected Versions

Neos: 7.3, 8.1

UI: 8.1.2

**Comment by alexander-nitsche** [comment] 2023-01-26 11:33
I can reproduce the issue. With this bash script and ddev as prerequisite you can bring up an according Neos 7 instance with
```
PROJECT_FOLDER=<project-name> neos-7.sh
```
e.g.
```
PROJECT_FOLDER=my-website-2022 neos-7.sh
```

neos-7.sh:
```bash
#!/bin/bash

thisDir=$(realpath .)

#
# Install Neos 7 with sitepackage "Code Q Neos-Skeleton" in DDEV environment
#
# @see https://docs.neos.io/cms/installation-development-setup/all-platforms-using-ddev-and-docker
# @see https://github.com/code-q-web-factory/Neos-Skeleton/blob/master/docs/GETTING_STARTED.md
#
function installDdevDev()
{
  local projectFolder="${PROJECT_FOLDER}"
  local neosPackageName="${NEOS_PACKAGE_NAME}"
  local composerPackageName="${COMPOSER_PACKAGE_NAME}"

  [ -z "${projectFolder}" ] && projectFolder="."
  local projectDir=$(realpath "${projectFolder}")
  local projectFolderName=$(basename "${projectDir}")

  if [ -z "$neosPackageName" ]; then
    neosPackageName=$(convertToUpperCamelCase "${projectFolderName}")
    neosPackageName="${neosPackageName}.Site"
  fi

  if [ -z "$composerPackageName" ]; then
    composerPackageName=$(convertToLowerCaseWithoutDashes "${projectFolderName}")
    composerPackageName="${composerPackageName}\/site"
  fi

  if isDirectoryWithFiles "${projectFolder}"; then
    echo "Folder \"${projectFolder}\" already exists and is not empty. Choose a different folder by the environment variable PROJECT_FOLDER. Aborting Neos installation."
    exit
  fi

  git clone git@github.com:code-q-web-factory/Neos-Skeleton.git ${projectFolder}
  cd ${projectDir}
  mv DistributionPackages/CodeQ.Site DistributionPackages/${neosPackageName}
  find . -type f -name 'composer.json' | xargs sed -i "s/codeq\/site/${composerPackageName}/g"
  find ./DistributionPackages/${neosPackageName} -type f | xargs sed -i "s/CodeQ\.Site/${neosPackageName}/g"
  rm -Rf docs
  rm -rf .git && git init
  ddev config \
    --project-type="php" \
    --docroot="Web" \
    --create-docroot \
    --database="mariadb:10.5" \
    --php-version="7.4" \
    --timezone="Europe/Berlin" \
    --web-environment-add="FLOW_CONTEXT=Development/Local"
  ddev composer install
  git add .
  git commit -m "TASK: Initialize Neos 7 project with Code Q Neos-Skeleton"

  mkdir -p Configuration/Development/Local
  tee Configuration/Development/Local/Settings.yaml > /dev/null << EOT
Neos:
  Imagine:
    driver: Imagick
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: db
        user: db
        password: db
        host: db
    http:
      trustedProxies:
        proxies: "*"
EOT

  ddev launch

  cat << EOT
Fetch installation password with
---
cd ${projectDir} && ddev exec cat /var/www/html/Data/SetupPassword.txt && cd -
---
EOT

  cd "${thisDir}"
}

function convertToUpperCamelCase()
{
  local input="$1"
  input=$(echo "$input" | sed -r 's/^(.)|-(.)/\U\1\U\2/g')
  echo "$input"
}

function convertToLowerCaseWithoutDashes()
{
  local input="$1"
  input=$(echo "$input" | sed -r 's/-//g')
  input=${input,,}
  echo "$input"
}

function isDirectoryWithFiles()
{
  local directory="$1"
  if [ ! -d "$directory" ] || find "$directory" -maxdepth 0 -empty | grep -q "."; then
    return 1
  else
    return 0
  fi
}

installDdevDev
```

**Comment by rolandschuetz** [comment] 2023-04-15 19:48
The problem is fixed by Felix from Code Q with this PR:
https://github.com/code-q-web-factory/Neos-Skeleton/pull/30/files

Can you please check, that is also fixed in your project with this code change.

**Comment by alexander-nitsche** [comment] 2023-04-16 09:54
I can confirm that this commit fixes the problem in Neos 7 LTS.

It would be interesting to get some background information on this problem, which could be interesting for any Neos developer, but especially for beginners.

**Comment by alexander-nitsche** [comment] 2023-04-17 19:30
While analyzing the Neos / Flow cache, I noticed that with PR [#30](https://github.com/code-q-web-factory/Neos-Skeleton/pull/30), the footer is cached twice: (1) The footer of the homepage (which is editable) and (2) the footer of every other page (which is not editable).

**Comment by Sebobo** [comment] 2023-04-18 06:48
I would close this now as the issues are not in this repo.

**Closed as completed by Sebobo** 2023-04-18 06:48 UTC
Labels: Bug
