### ISSUE TITLE
SelectorBoxEditor does not set choosen data-source value

### ISSUE THREAD

**Issue by DrNik** [neos/neos-ui#1536] opened 2018-01-16 13:04 UTC
The dropdown of SelectorBoxEditor gets emptied out at either "apply" or "reload", when provisioned via data-source.
The node property gets stored with the choosen value correctly,  though.

Tested versions:

- Neos: 3.3.3
- Neos.UI: 1.0.4

Nicola

**Comment by DrillSergeant** [comment] 2018-01-16 13:40
I can confirm this behaviour (same versions). Here is the yaml-definition of my field:
```    
    zoom:
      type: integer
      defaultValue: 14
      ui:
        label: i18n
        reloadIfChanged: TRUE
        inspector:
          group: map
          position: 30
          editor: Content/Inspector/Editors/SelectBoxEditor
          editorOptions:
            values:
              0:
                label: 'Auto'
              1:
                label: '1'
              2:
                label: '2'
```

**Comment by DrNik** [comment] 2018-01-19 13:11
UPDATE: by chance I discovered that the SelectorBoxEditor to work wants strings, not integers.

Don't know if it is wanted or a bug but casting keys as string makes the selector work on both new and old ui (where I faced the same issue and where I could discover the "fix").

Nicola

**Comment by DrillSergeant** [comment] 2018-01-19 13:38
@DrNik , you mean this should work?

```    
    zoom:
      type: integer
      defaultValue: 14
      ui:
        label: i18n
        reloadIfChanged: TRUE
        inspector:
          group: map
          position: 30
          editor: Content/Inspector/Editors/SelectBoxEditor
          editorOptions:
            values:
              '0':
                label: 'Auto'
              '1':
                label: '1'
              '2':
                label: '2'
```

Still the same behaviour on my side.

**Comment by DrNik** [comment] 2018-01-19 14:43
@DrillSergeant did not try with static options sorry, I am filling the SelectorBox from a data-source, so:

**this does not work**:` [{"value":165,"label":"whatever"}]`

**this does work**: `[{"value":"165","label":"whatever"}]`

and I only casted the key with `(string)` during data source array building.

Hope it helps,
Nicola

**Comment by DrNik** [comment] 2018-01-22 09:32
A little further update, that I think could be helpful.
After further digging I realized that the **data-source data type has to match the data type configured in the node type property (.yaml)**.

Maybe it's an obvious discovery but due it can lead to tricky results I felt it's worthy to write it down ;).

Bests,
Nicola

**Comment by DrillSergeant** [comment] 2018-01-22 09:36
In my case (see my config above, those with integer values, not those with string values) the property is of type integer same as the values but still did not work.

**Comment by DrNik** [comment] 2018-01-22 09:50
@DrillSergeant yes I noticed that, and it still puzzles me, but that's why I highlighted the "data-source" part in my comment as I was facing the issue on data-source feeded SelectorBoxEditors.

A lognshot: have you tried moving completely to strings (as in your second example zoom.type = integer, still).

**Comment by DrillSergeant** [comment] 2018-01-22 10:32
@DrNik Wow, indeed, switching the property-type to string and using string-values did work: the selectbox shows the current value.
Question is now: is this a bug or a contraint to use it only for string-type properties?
My "zoom" property feels better as integer, but I can handle it as string if must be for die SelectorBoxEditor.

**Comment by DrNik** [comment] 2018-01-22 10:37
Imho feels like a bug due to via data-sources it works with integers, but being no core dev or react-ui dev I leave the last word to them.

**Comment by dimaip** [comment] 2018-02-19 17:48
So what do we do about this? Is that a bug really?

**Comment by DrNik** [comment] 2018-02-19 17:59
@dimaip I do not think is a bug, at least for my use case, i.e. populating the SelectorEditor via DataSource. I'm not so sure about @DrillSergeant use case as he was stating that using integer values and polulating SelectorEditor statically wasn't working.
Imho the behaviour should be consistent among use cases and it seems not to be, but I could be wrong.

Thanks

**Comment by lorenzulrich** [comment] 2018-02-19 20:17
At least when you try referencing an entity though dataSource, the selection is immediately lost upon clicking "Apply" and you can't save it. So IMO it's clearly a bug. But I'm not sure if we need separate issues for the different (failing) use-cases.

**Comment by DrillSergeant** [comment] 2018-02-20 05:55
@dimaip I consider it a bug that it's not possible to  have integer values. As @lorenzulrich mentioned it's even worse with entitiy references because the data is not even saved to database when hitting the apply-button. Maybe 2 different issues, not sure.

**Comment by dimaip** [comment] 2018-03-02 21:16
Should be fixed in master. Please test and re-open if not.

**Comment by DrillSergeant** [comment] 2018-03-05 08:45
@dimaip Nice, the value is saved now and displayed correctly when reloading the page: 
![image](https://user-images.githubusercontent.com/883552/36965320-9d8313cc-2059-11e8-8804-28d8da9f302c.png)

But when opening the selectboxEditor the current value is not set:
![image](https://user-images.githubusercontent.com/883552/36965373-c770ebbe-2059-11e8-942c-137496dddb39.png)

 and when I just close it (without clicking any value), the value seems to get cleared.
![image](https://user-images.githubusercontent.com/883552/36965413-e016178e-2059-11e8-8ff1-eec9a8a0aa91.png)

**Comment by DrillSergeant** [comment] 2018-03-05 08:46
How to repoen this issue? I see no button for that.

**Comment by dimaip** [comment] 2018-03-06 11:22
@DrillSergeant I don't think that the issue you described actually relates to datasources, does it?

**Comment by DrillSergeant** [comment] 2018-03-07 07:16
@dimaip yes it might be just a bug in the seletboxEditor frontend-control. I mentioned it here because the behaviour almost the same as described in initial issue report here.
Shall I rather open a new issue for this instead?

**Comment by dimaip** [comment] 2018-03-07 07:38
@DrillSergeant yes please, would be helpful if you could re-test with plain selectbox and open a separate issue describing the results of your findings.

**Closed by dimaip** 2018-03-07 07:38 UTC
Labels: Bug
