### ISSUE TITLE
Support recent changes for the Asset Editor

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#1208] opened 2017-11-03 17:15 UTC
See https://github.com/neos/neos-development-collection/pull/1727

This should be supported in 1.0 https://github.com/neos/neos-ui/issues/687

**Comment by dfeyer** [comment] 2017-12-07 11:44
In relation with https://github.com/neos/neos-ui/issues/1390

**Comment by dimaip** [comment] 2017-12-13 05:59
So this is a duplicate of #1390 basically? Will leave that one open.
Re-open if I'm wrong.

**Closed by dimaip** 2017-12-13 05:59 UTC
Labels: Enhancement, Frontend / Frontend-API, UI & UX
