### ISSUE TITLE
Path to referenced node contains workspace

### ISSUE THREAD

**Issue by alex-boehm** [neos/neos-ui#1997] opened 2018-07-11 08:29 UTC
### Description
![grafik](https://user-images.githubusercontent.com/5336386/42559499-90a311b6-84f4-11e8-93c5-1ed9db36f21b.png)

### Steps to Reproduce

1. Add a node with special chars in title (like &)
2. Create a field of type reference for the node type
3. Select node type with special char

#### Expected behavior
Only shows the path once without user workspace

#### Actual behavior
Shown twice with user workspace

[What actually happened]

### Affected Versions

Neos: 4.0.6

UI: 1.2.3

**Comment by skurfuerst** [comment] 2018-07-11 18:47
Hey,

while I am able to reproduce #1996, I am not able to reproduce this issue. Can you check in https://github.com/neos/neos-ui/blob/master/packages/neos-ui-backend-connector/src/Endpoints/index.js#L235 whether the URL is correctly built?

<img width="1140" alt="other elements - features - neos demo site 2018-07-11 20-44-42" src="https://user-images.githubusercontent.com/190777/42592892-464bd65a-854b-11e8-8436-b70ccd5d529a.png">

All the best, Sebastian

**Comment by dimaip** [comment] 2018-08-13 21:11
I'm not able to reproduce the issue either, so I'll close it for now. Feel free to re-open.

**Closed by dimaip** 2018-08-13 21:11 UTC
