### ISSUE TITLE
Crop is not enforced when uploading images

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-ui#1525] opened 2018-01-09 15:11 UTC
When configuring an image property with only one crop setting like:
```yaml
  properties:
    'teaserImage':
      type: 'Neos\Media\Domain\Model\ImageInterface'
      ui:
        inspector:
          editorOptions:
            features:
              crop: true
            crop:
              aspectRatio:
                locked:
                  width: 8
                  height: 1
```
The resulting image should be cropped automatically to the given ratio. Instead the crop settings are ignored, *unless the crop editor is actively used*.

**Comment by johannessteu** [comment] 2018-02-09 13:50
Should we force open the crop editor here so the editor notices that the uploaded image will be cropped? If not he might uploads an image and doesn't really recognize that it is force cropped

**Comment by bwaidelich** [comment] 2018-02-09 14:02
> Should we force open the crop editor here

yes, I think that would be a nice behavior

**Comment by DrillSergeant** [comment] 2018-03-26 10:38
Not sure if I shall put that into another issue, but also defaultOption does not work:

```
  properties:
    teaserImage:
      type: Neos\Media\Domain\Model\ImageInterface
      ui:
        label: i18n
        inspector:
          group: 'teaser'
          editorOptions:
            features:
              crop: TRUE
            crop:
              aspectRatio:
                options:
                  teaser:
                    width: 1000
                    height: 500
                    label: 'Teaser'
                enableOriginal: TRUE
                allowCustom: TRUE
                defaultOption: 'teaser'
```

I expect here that the image is cropped to 1000/500 when I select am image from the media library or upload an image. But in both cases no cropping at all happens.

I comment into this issue because it may be caused by the same thing. If not, I can open another ticket.

**Comment by dimaip** [comment] 2018-04-10 06:12
Oh sorry, GitHub closed it for me :)

**Comment by DrillSergeant** [comment] 2018-04-16 10:44
I just realized, it's not working as expected. The cropping area is selected when you open the cropping-window. But you need to click into it to apply cropping.
I would expect that the image is cropped already (just by uploading or selecting it) with any clicking on the cropping-tool neeed.

**Comment by dimaip** [comment] 2018-04-16 11:56
@DrillSergeant yes, that's right, as said the fix that I created only partly resolves the problem, thus the issue is still open. Will try to tackle it this week, but auto cropping is not that easy.

**Closed** 2018-04-27 07:43 UTC
Labels: Bug, Editor Ui Regression
