### ISSUE TITLE
Labels and icons in ContentCollections

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#2503] opened 2019-05-21 12:41 UTC
At the moment, it is not possible to define own icon and/or label for `Neos.Neos:ContentCollection`.

**Comment by markusguenther** [comment] 2019-05-23 13:12
Ok after a call with Jon it is now clearer what he wants to achieve.

The Problem is that you can always define icons and labels for nodes or new node types, but not for the ```Neos.Neos:ContentCollection``` itself.

<img width="317" alt="Other_elements_-_Features_-_Neos_Demo_Site_-_Vivaldi" src="https://user-images.githubusercontent.com/1014126/58255365-1f353a00-7d6d-11e9-9ee0-c517486c50a5.png">

So it is more or less a feature to resolve this inconsistency.
It would be better to have own labels sometimes and configure own icons than the folder.

**Comment by markusguenther** [comment] 2019-05-23 15:08
Before I dive deeper into the rendering of the content tree.
Is it ok to adjust the icon and label like that for the content collections? Or any other suggestions?

```
'Neos.NodeTypes:Page':
  childNodes:
    'main':
      ui:
        icon: 'icon-star'
        label: 'Main'
    'teaser':
      type: 'Neos.Neos:ContentCollection'
      ui:
        icon: 'icon-star'
        label: 'Teaser'
      constraints:
        nodeTypes:
          '*': FALSE
          'Neos.NodeTypes:Headline': TRUE
          'Neos.NodeTypes:Text': TRUE
          'Neos.NodeTypes:Image': TRUE
```

I am still searching the piece of code where the node label is generated because it does not happen in the node component of the tree itself. But will try to investigate that.

**Comment by danielkestler** [comment] 2019-05-24 06:27
Shouldn't you override it like ...?

```
'Neos.Neos:ContentCollection':
  ui:
    icon: 'icon-star'
```
And if you need different "types" of ContentCollections, just make your own and inherit from Neos.Neos:ContentCollection ...?

**Comment by dimaip** [comment] 2019-08-30 05:31
What @danielkestler suggest is correct, therefore I'm closing this issue. Please re-open if I'm wrong.

**Comment by jonnitto** [comment] 2019-09-01 21:49
Please re-open it. That's exactly the point. It is not possible to set the label or the icon. For example, this don't work as expected:
```yaml

**Comment by dimaip** [comment] 2019-09-02 04:55
Thank you for the sample config, now it would be much easier to reproduce it.

**Comment by dimaip** [comment] 2019-10-14 15:31
I'll take this one

**Comment by dimaip** [comment] 2019-10-15 15:34
@jonnitto I just tested both with 2.x and with 5.0, and I get the expected behaviour with your code example:

![image](https://user-images.githubusercontent.com/837032/66846336-fa3aa100-ef71-11e9-9bb7-67e3c8bc3426.png)

**Closed by dimaip** 2019-10-15 15:34 UTC
Labels: Bug, UI & UX
