### ISSUE TITLE
BUG: Children of previously opened node are missing after search

### ISSUE THREAD

**Issue by manuelmeister** [neos/neos-ui#3733] opened 2024-03-05 09:35 UTC
### Description

Child nodes are not visible after searching. I was 

### Steps to Reproduce

Could be reproduced on current docs.neos.io

1. Expand a parent node
2. Collapse the node
3. Search for anything
4. Clear search
5. Expand the previously opened node

#### Expected behavior

All children are displayed

#### Actual behavior

Childnodes are not shown

https://github.com/neos/neos-ui/assets/3001985/250a7f90-1688-4435-99a2-8abe66af3f73

### "Workaround"

Reload the page

### Affected Versions

Neos: 8.3.6
UI: 8.3.6

(probably longer)

**Comment by grebaldi** [comment] 2024-07-02 17:13
Hi @manuelmeister,

thanks for reporting! I'm able to reproduce this issue. However, I'm closing this as a duplicate of #2583, so any further progress will be tracked there.

 If you object, please let me know :)

**Closed as completed by grebaldi** 2024-07-02 17:13 UTC
Labels: Bug, 8.3
