### ISSUE TITLE
Hide the inspector panel should close crop mode

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#853] opened 2017-09-01 19:55 UTC
Steps to reproduce:
1) Click on an image node
2) Open the crop mode
3) hide the inspector pane

Now the crop window is still active. This should also close. Right now also the z-index for the close button is very high and will overlap the publish menu
<img width="928" alt="bildschirmfoto 2017-09-01 um 21 53 53" src="https://user-images.githubusercontent.com/769789/29985672-3fbf8700-8f60-11e7-99c8-e3a270912b94.png">

**Comment by dimaip** [comment] 2017-09-14 19:05
@johannessteu gave this a thought and wonder if that's really a bug? E.g. I might want to hide inspector panel while cropping to have more room for the image and to be distracted less...
Also can't reproduce the z-index problem.
Will un-assign from 1.0 sprint for now.

**Comment by markusguenther** [comment] 2018-04-10 16:00
![ezgif com-resize](https://user-images.githubusercontent.com/1014126/38568466-041dd9ae-3ce9-11e8-9afc-c69d2b5d9bba.gif)


@johannessteu guess we can close this issue right? Or do you have special circumstances?

**Comment by markusguenther** [comment] 2018-04-22 20:11
@johannessteu @dimaip Ping :)

**Comment by dimaip** [comment] 2018-04-29 10:57
Yes, can confirm it works!

**Closed by dimaip** 2018-04-29 10:57 UTC
Labels: Bug
