### ISSUE TITLE
Relogin after timeout reloads complete neos ui within inner iframe

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#1225] opened 2017-11-08 09:23 UTC
After some time of inactivity the neos editing backend asks for credentials. When I enter them and thus relogin, the site is reloaded. However, instead of just reloading the whole page, the neos ui (with all controls) and the webpage being edited is rendered inside of the inner iframe where only the webpage should be displayed.

Can be fixed by reloading the page in the browser.

**Comment by johannessteu** [comment] 2017-11-13 11:17
Can't reproduce. Anyone else?

**Comment by klfman** [comment] 2017-12-05 16:16
Should be a similar rendering problem as https://github.com/neos/neos-ui/issues/1332. Maybe I also had a problem in my code and it wasn't the relogon? Can't say

**Comment by mstruebing** [comment] 2017-12-19 13:26
Can't reproduce either. Closing this for now. Feel free to open again if the same issue occurs for you.

**Closed by mstruebing** 2017-12-19 13:26 UTC

**Comment by klfman** [comment] 2017-12-20 09:06
This doesn't happen to me anymore. I suspect that I misinterpreted this one for https://github.com/neos/neos-ui/issues/1332
