### ISSUE TITLE
Aloha format options disappear upon text selection (inline editing)

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#1441] opened 2017-12-14 14:06 UTC
By configuring an inline editable text property with:
```
ui:
  aloha:
    'format':
        'strong': true
         'em': true
```

I enabled two buttons for the editor to change the appearance of the text. This works like a charm.

However: If I select the whole text from the right to the left up to the leftmost border of the inline editable field, the formating buttons disappear. Any other way of selecting the text works (e.g. parts of it, double clicking, cmd or ctrl + a).

**affects** (I'm working with): dev-master, commit 52a0bda

**Comment by dimaip** [comment] 2017-12-15 06:40
Duplicate of #1409

**Closed by dimaip** 2017-12-15 06:40 UTC
