### ISSUE TITLE
Language label in node creation dialog missing

### ISSUE THREAD

**Issue by danielkestler** [neos/neos-ui#1472] opened 2017-12-21 11:12 UTC
![bildschirmfoto 2017-12-21 um 12 10 02](https://user-images.githubusercontent.com/3976405/34253515-3cb3c14a-e648-11e7-88cd-fb5db69d8ddd.png)

**Comment by mstruebing** [comment] 2017-12-21 12:22
I can't reproduce it, either on dev-distribution nor on base-distribution, anyone else?

**Comment by dimaip** [comment] 2017-12-22 07:31
It may only happen on 3.2 or earlier. As we don't support those versions with the new UI, closing.

**Comment by danielkestler** [comment] 2018-01-04 17:43
Sorry to say, this issue still occurs to me, even in new installations. Did you try it in a language other than English?

**Comment by dimaip** [comment] 2018-01-05 05:31
Yep I noticed it too. It happens if your language has no fallback to English. Reopening.

**Comment by markusguenther** [comment] 2018-04-09 13:14
It is possible that this issue is still fixed? Can not reproduce this with danish, english, german and polish. Also tried to adjust labels to verify that, but don't get the bug here.

@danielkestler If it is still relevant please give us a bit feedback :)

**Comment by markusguenther** [comment] 2018-05-04 08:07
@danielkestler Ping :)

@dimaip @mstruebing I think this is not an issue anymore. Can you double check that and close the issue?

**Comment by dimaip** [comment] 2018-05-04 12:12
I can confirm it's fixed now.

**Closed by dimaip** 2018-05-04 12:12 UTC
Labels: Bug, Good first issue, to validate / retest

**Comment by danielkestler** [comment] 2018-10-03 20:09
Sorry, totally missed this thread. It is fixed now, thanks.
