### ISSUE TITLE
Bug: Line break in header row/column option of table dropdown

### ISSUE THREAD

**Issue by esdete2** [neos/neos-ui#3035] opened 2022-02-21 09:19 UTC
### Description

The label of header row/column option is below the corresponding checkbox.

### Steps to Reproduce

1. Place a table inside of an inline text element
2. Click on the row or column dropdown in ckeditor options

#### Expected behavior

The label should be next to the checkbox.

#### Actual behavior

![Bildschirmfoto 2022-02-21 um 10 01 35](https://user-images.githubusercontent.com/34043608/154922149-be8c79b1-23b0-4cfa-abaa-0e127acbcf5e.png)

In this commit the checkbox is changed from `display: inline-block` to `display: block`, which causes it to take up the full width:  https://github.com/neos/neos-ui/commit/5647b84f24492762f019273ac001a34850f2fac7#diff-715d745c65e8adde10e1120c36b7f62567b0d5bb2b9d9bf3cd1429542d61d0e6R4

### Affected Versions

Neos: 7.3.1

UI: 7.3.1

**Comment by markusguenther** [comment] 2022-02-22 19:42
Thanks for reporting the issue. Tested that and can confirm the issue :)

**Comment by markusguenther** [comment] 2022-02-22 19:47
Should also affect all Neos versions since 5.3 BTW.

**Comment by markusguenther** [comment] 2022-02-22 20:18
This is a regression of #2976 but will be fixed in an upcoming version of the UI up from version 5.3.

**Closed** 2022-03-01 09:26 UTC
Labels: Bug, 5.3
