### ISSUE TITLE
"Edit / Preview" buttons slides as buttons are clicked

### ISSUE THREAD

**Issue by sorenmalling** [neos/neos-ui#688] opened 2017-04-13 09:56 UTC
**Reproduce**
1. Click the "Edit / Preview" and display the **Editing mode**  and **Preview Central**
2. Click one of the Editig mode or previews and see the buttons slide from side to side, when click

**Other information**
It seems related to the css `transform: translate3d(..)` of the div inside `scroll-horizontal`

**Browser**
Google Chrome 
Version 57.0.2987.133 (64-bit)

**Comment by skurfuerst** [comment] 2017-04-13 10:02
Hey @sorenmalling,

thanks for your valuable feedback!

Could you add a short animated gif explaining the issue, f.e. by using [KAP](https://getkap.co/)?

Thanks, and all the best,
Sebastian

**Comment by sorenmalling** [comment] 2017-04-13 10:30
![neos-ui-sliding-buttons](https://cloud.githubusercontent.com/assets/531918/25001276/0073ebe8-2045-11e7-81ce-7fbe44b61459.gif)

**Comment by skurfuerst** [comment] 2017-04-13 10:52
Fancy 💃 interestingly I didn't see this yet

**Comment by gerhard-boden** [comment] 2017-05-14 15:32
So I did some research and it turns out that the error comes from a bug within external component for horizontal sliding:
https://github.com/hew/react-scroll-horizontal/issues/10

The proposed bugfix within the issue has already been merged, but does not fix our problem. Plus the component does not seem to be "heavily maintained" in general and needs a rewrite according to the creator.

I already tried replacing the component, but there aren't that many good lightweight horizontal scroll components out there as one would suppose. Already tried to replace it with a similar one, but didn't work right away so I wanted to gather some feedback first how we should proceed with this on.

As I see it our options are:

1. Help the creator of the used component to fix the issue
2. Find a different component and implement it
3. Write our own horizontal scroll component

**Comment by dfeyer** [comment] 2017-05-17 06:37
Hi, I think we can just abandon, the horizontal slider, it's a pure non sense in term of UX, a two select component, will work better

**Comment by hew** [comment] 2017-05-26 09:12
@gerhard-boden What's the issue (you are having)? I can't tell from the gif what exactly is going on. Regardless, I'll try to push a patch to the lib in the near future that addresses hew/react-scroll-horizontal#10. This lib definitely hasn't been maintained heavily up until this point, but as I see that no other lib has popped up (I honestly thought one would) but people are actually using this thing, I I'll try and be a bit more responsive.

**Comment by gerhard-boden** [comment] 2017-05-28 14:42
@hew Thanks a lot for reacting to this issue! 
I've talked about this with two colleagues and as it currently seems we are going to drop the ``react-scroll-horizontal`` component altogether. The decision was mostly based on the necessary UX for our use case and less about the technical problem that occurred (since you've asked about details about the issue above: The buttons inside the scroll horizontal scroll container started sliding when the containing elements where smaller than the container itself, after focusing an element).

I went ahead and roughly implemented a classic carousel component instead, which fits better for our "row of buttons" (since the user instantly sees that there are more to chose from)
![new_editmode_selector](https://cloud.githubusercontent.com/assets/10533739/26529621/94b1e480-43c3-11e7-9b21-61aa35e6bca4.gif)

But of course you can nevertheless contact me in case you need more information about the bug or on how to reproduce it.

**Comment by hew** [comment] 2017-05-29 20:09
@gerhard-boden Ah I see the issue now. Glad to see you got things sorted out. 👍

**Closed** 2017-07-05 06:58 UTC
Labels: Bug, in progress
