### ISSUE TITLE
color indicator in page and structure tree differ from old ui and offsets marked element

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#1079] opened 2017-09-29 12:09 UTC
old UI
![screen shot 2017-09-29 at 14 02 17](https://user-images.githubusercontent.com/683773/31015200-25f4fdda-a51f-11e7-8e3a-8ebcf96962ca.png)

Always to the far right not aligned with the text.

new UI
![screen shot 2017-09-29 at 14 00 25](https://user-images.githubusercontent.com/683773/31015204-2ebc4b1c-a51f-11e7-9a69-5cc1d1964e75.png)

Aligned with the item text also offsetting the text a couple of pixels, destroying the horizontal alignment with its siblings.

To discuss:

I personally like the version of the old ui better, as it keeps the tree cleaner. Kind of reminds me of the feature in an IDE. Feels better.

**Comment by dimaip** [comment] 2017-09-29 12:19
Duplicate of #911

**Closed by dimaip** 2017-09-29 12:19 UTC
Labels: Bug, Discussion
