### ISSUE TITLE
discard is not doing anything after removing an image from a node

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#1077] opened 2017-09-29 11:45 UTC
![sep-29-2017 13-40-10](https://user-images.githubusercontent.com/683773/31014563-ce7773ec-a51b-11e7-90b6-989e037ce35b.gif)

I removed an image from a custom node (content collection), which renders some kind of icon in the corner of a section. After hitting apply the publish button turns organge (which is correct). If I hit discard or discard all nothing happens. No reaction of the ui, no reloading of the iframe. Nothing. The button stays orange. Sometimes this is accompanied by an error message.

![screen shot 2017-09-29 at 13 44 35](https://user-images.githubusercontent.com/683773/31014671-66cfe782-a51c-11e7-9e52-ae8b40f7597c.png)

**Comment by grebaldi** [comment] 2017-09-29 12:00
The error message is addressed in https://github.com/neos/neos-development-collection/pull/1711

**Comment by crazydrecksack** [comment] 2017-09-29 12:19
ok

**Comment by dimaip** [comment] 2017-10-07 09:01
So is this fixed? Anyways, can't reproduce it myself.

**Comment by kitsunet** [comment] 2017-11-05 15:22
Also can't reproduce.

**Closed** 2017-11-06 06:27 UTC
Labels: Bug, to validate / retest
