### ISSUE TITLE
Translation for font styling options (aloha) missing

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#1442] opened 2017-12-14 14:17 UTC
I'm working with the German translation of the neos backend. The translations of the font styling options (aloha) seem to be still missing. See here:

![screen shot 2017-12-14 at 15 11 26](https://user-images.githubusercontent.com/9661367/33996377-521e67d6-e0e1-11e7-9e2a-f5afb9e5a4e5.png)

"B" (Bold) should be "F" (Fett), "I" (Italic) should be "K" (Kursiv) and so on

**Comment by dimaip** [comment] 2017-12-15 06:38
Duplicate of #1422

**Closed by dimaip** 2017-12-15 06:38 UTC
