### ISSUE TITLE
Apostrophes are merged with text

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#2442] opened 2019-04-02 09:38 UTC
### Description

After an upgrade of neos-ui from 1.4.1 to 3.2.1 apostrophes are merged with the corresponding text in neos-ui components (not on the rendered content of the page itself!).
To see the problem, use an apostrophe in a title that will show up in the page tree on the left (for example a title of a document, let's say "so geht´s"). It must be an apostrophe like a french accent (not a single quote). It will be merged with the text regardless of the following letter (-> also with consonants).

Interesting to note: when reloading the page, for about a second the title is shown as entered, after the font loads, it is merged with the word.

### Steps to Reproduce

1. Use an apostrophe in a title that will show up in the page tree on the left (for example a title of a document, let's say "so geht´s"). It must be an apostrophe like a french accent.
2. Reload the page
3. For about a second the title is shown as entered, after the font loads, it is merged with the word

#### Expected behavior

Apostrophes are not merged with words if they were not entered in a way that the editor decided to enter, let's say, french letters.

#### Actual behavior

Display in the page tree after the font loaded:
![Screenshot 2019-03-29 at 12 11 50](https://user-images.githubusercontent.com/9661367/55392351-6eb07400-553b-11e9-8ca4-f2f471028ca4.png)

In the page content (rendered correctly as entered):
![Screenshot 2019-04-02 at 11 25 37](https://user-images.githubusercontent.com/9661367/55392355-6f490a80-553b-11e9-8971-5e804e6f7968.png)

In the inspector (the same property of the image above) is rendered wrong:
![Screenshot 2019-04-02 at 11 25 42](https://user-images.githubusercontent.com/9661367/55392356-6f490a80-553b-11e9-8df1-04bfcc2de29a.png)

### Affected Versions

Neos: 4.2.9

UI: 3.3.0

**Comment by jonnitto** [comment] 2019-04-02 10:01
From my point of view, you are trying to use the wrong typographic symbol. The character you are using is not an [apostrophe](https://en.wikipedia.org/wiki/Apostrophe), it is an [acute accent]( https://en.wikipedia.org/wiki/Acute_accent)

**Comment by klfman** [comment] 2019-04-02 10:08
@jonnitto You are right, it is not the right symbol. But that's just the symptom :) Should be fixed nonetheless, because neos-ui rendering of properties and rendering on the page content should not differ.

**Comment by markusguenther** [comment] 2019-04-04 08:09
It seams that is more or less part of the font. You already described the behaviour that everything in fine until the font is loaded. We had a PR that adjusts the font of the backend.

We had two different fonts in the backend depending on the react rendered components and the fluid driven stuff. Not sure if this is now already using one single font. But there was a discussion to keep the "old" font in both context until the design team has decided which font we choose.

**Comment by dimaip** [comment] 2019-04-04 08:13
Yes, we now use the old font everywhere. You can try to find a newer version of it and replace it, but I'm not sure there's actually a problem here, accent glyph is supposed to be merged with the letter, as I understand.

**Comment by danielkestler** [comment] 2019-04-04 11:12
Yes, I also think so. I don't even know, if the font's behaviour is right in doing so or wrong – it just behaves like it and it does not really matter IMO as the apostrophe-character is not entered correctly ;-)

**Comment by kdambekalns** [comment] 2019-09-12 07:06
Just as a side-note: The behavior in the editor of discuss.neos.io is the same, when entering backticks (for code formatting). 🤷‍♂️

**Comment by kdambekalns** [comment] 2019-09-12 07:25
I can confirm the behavior is _wrong_: Typing

    So geht`SPACEs

should result in

<img width="213" alt="Screenshot 2019-09-12 at 09 12 24" src="https://user-images.githubusercontent.com/95873/64761936-8275f280-d53d-11e9-9d50-8ed7f98a565b.png">

as shown in the document rednering. But the inspector shows it as

<img width="80" alt="Screenshot 2019-09-12 at 09 12 32" src="https://user-images.githubusercontent.com/95873/64761921-7b4ee480-d53d-11e9-8c03-04d6dfe3e82f.png">

For "real" accented chars entered like this:

![accented-chars](https://user-images.githubusercontent.com/95873/64762794-0e3c4e80-d53f-11e9-8e25-54a0095556fa.gif)

the behavior should be foreseeable, but:

<img width="69" alt="Screenshot 2019-09-12 at 09 24 32" src="https://user-images.githubusercontent.com/95873/64762827-26ac6900-d53f-11e9-9997-bd6e7a5f10db.png">

Two á looking the same.

Ergo: Wrong.

**Comment by kdambekalns** [comment] 2019-09-12 07:42
Conclusion: The "Noto Sans" font _is_ the culprit (in Neos as well as discuss.neos.io.) And disabling ligatures through CSS does _not_ help.

Might be https://github.com/googlefonts/noto-fonts/issues/1553

**Comment by grebaldi** [comment] 2021-07-17 12:24
Closing this, since it's actually `Noto Sans`-related.

**Closed by grebaldi** 2021-07-17 12:24 UTC
