### ISSUE TITLE
Loading Backend in iFrame

### ISSUE THREAD

**Issue by samuelhauser** [neos/neos-ui#1332] opened 2017-11-22 16:04 UTC
If you have an error in your page (e.g. missing fusion configuration for a nodetype), the backend is loadet multiple times in the iframe.

**Comment by klfman** [comment] 2017-12-05 16:16
See https://github.com/neos/neos-ui/issues/1225 where I reported a similar issue

**Comment by mstruebing** [comment] 2017-12-19 13:36
Can't reproduce but I remember this error.
Anyone else?

**Comment by skurfuerst** [comment] 2017-12-21 22:12
Hey @samuelhauser,
we believe this is fixed with the stable 1.0.0 release together with Neos 3.3.

Please re-open as soon as the error appears again.
Thanks <3
Sebastian

**Closed by skurfuerst** 2017-12-21 22:12 UTC
Labels: Bug

**Comment by samuelhauser** [comment] 2017-12-22 11:03
Hey @skurfuerst ,
Yesterday I had the same error again (release 1.0.3). I can't tell you exactly what I was doing. Could not reproduce the error, but it doesn't seem to be fixed yet.

**Comment by samuelhauser** [comment] 2017-12-22 11:04
PS: It was not the same behaviour as #1225
