### ISSUE TITLE
PublishDropDown stays in state "Publish to live (X)" after "Discard" or "Discard all"

### ISSUE THREAD

**Issue by KPeschke** [neos/neos-ui#1853] opened 2018-05-04 15:36 UTC
### Description

PublishDropDown stays in state "Publish to live (X)" after "Discard" or "Discard all".
If you publish or discard afterwards you get an exception (500 Internal Server Error).  PublishDropDown stays now in state "Discarding... (X)".

Reload the backend to fix the PublishDropDown state.

### Steps to Reproduce

1. create a new content node on a page
2. discard changes
3. confirm message

#### Expected behavior
PublishDropDown in state "Published - live"

#### Actual behavior
see description

### Affected Versions

Neos: 3.3.9
UI: (i noticed that) v1.0.11 - v1.0.14

**Comment by dimaip** [comment] 2018-05-04 16:47
Could you please post the backend error during publishing?

**Comment by KPeschke** [comment] 2018-05-04 18:34
#### On "DIscard all" i get a browser console error

```javascript
uncaught at watchServerFeedback 
 at takeEvery 
 at  
 Error: Key must be a string
    at NodeTypesRegistry.get (https://***/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/JavaScript/Host.js?bust=d5c19111?008f431e:6:595213)
    at NodeTypesRegistry.getNodeType (https://***/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/JavaScript/Host.js?bust=d5c19111?008f431e:30:649188)
    at handleReload (https://***/_Resources/Static/Packages/Internezzo.ChildReload/JavaScript/ChildReload/Plugin.js?bust=1af9aa12?af307e93:128:56)
    at https://***/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/JavaScript/Host.js?bust=d5c19111?008f431e:30:617384
    at Array.forEach (<anonymous>)
    at https://***/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/JavaScript/Host.js?bust=d5c19111?008f431e:30:617362
    at Array.forEach (<anonymous>)
    at https://***/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/JavaScript/Host.js?bust=d5c19111?008f431e:30:617320
    at createTaskIterator (https://***/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/JavaScript/Host.js?bust=d5c19111?008f431e:6:567952)
    at runForkEffect (https://***/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/JavaScript/Host.js?bust=d5c19111?008f431e:6:571755)
```

#### After publishing:
in System_Developement.log

```
18-05-04 20:06:37 161715     ERROR     Flow                 Exception: Argument 1 passed to Neos\Neos\Service\PublishingService_Original::publishNode() must implement interface Neos\ContentRepository\Domain\Model\NodeInterface, null given - See also: 20180504200636661762.txt
```

in 20180504200636661762.txt

```
Exception: Argument 1 passed to Neos\Neos\Service\PublishingService_Original::publishNode() must implement interface Neos\ContentRepository\Domain\Model\NodeInterface, null given

38 Neos\Neos\Service\PublishingService_Original::publishNode(NULL, Neos\ContentRepository\Domain\Model\Workspace)
37 call_user_func_array(array|2|, array|2|)
36 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call("publishNode", array|2|)
35 Neos\Neos\Ui\Controller\BackendServiceController_Original::publishAction(array|3|, "live")
34 Neos\Neos\Ui\Controller\BackendServiceController::publishAction(array|3|, "live")
33 call_user_func_array(array|2|, array|2|)
32 Neos\Neos\Ui\Controller\BackendServiceController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
31 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
30 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
29 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
28 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
```

This is crapped from browser console output
<img width="1520" alt="bildschirmfoto 2018-05-04 um 20 24 09" src="https://user-images.githubusercontent.com/8969952/39645726-886701ce-4fd9-11e8-955b-b3561f2666e0.png">

I hope this helps you.

**Comment by dimaip** [comment] 2018-05-07 06:26
Thanks! I guess the error has got something to do with order of publishing nodes or something. Unfortunately I can't reproduce it here locally. Maybe more experienced PHP devs could step in? /cc random picks: @kdambekalns @bwaidelich

**Comment by dimaip** [comment] 2018-09-08 18:15
@KPeschke are you still able to reproduce this behavior with the latest version of Neos and UI?

**Comment by mstruebing** [comment] 2018-10-04 12:03
I'm closing this for now, can't reproduce.
Feel free to open it again if it persist to happen.

**Closed by mstruebing** 2018-10-04 12:03 UTC
Labels: Backend / Backend-API, Bug
