### ISSUE TITLE
Show something useful in the editable ToolTip text

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#929] opened 2017-09-09 09:32 UTC
Currently the tool-tip-text of an editable shows something like `WISYWIG-Editor, editor-n` - would be nice to have something more useful here like the node information or a help text ...

**Comment by dimaip** [comment] 2017-09-10 18:43
Agreed, confuses me too. I'd propose to remove those tooltips altogether...

**Comment by dimaip** [comment] 2017-09-12 08:09
Duplicate of #845 actually

**Closed by dimaip** 2017-09-12 08:09 UTC
Labels: Enhancement, Proposal
