### ISSUE TITLE
BUG: Grave Accent/Backticks in input fields / Noto Sans

### ISSUE THREAD

**Issue by pKallert** [neos/neos-ui#3006] opened 2021-12-22 10:51 UTC
### Description
When entering grave accents in an input field, they do not behave as single letters. This makes deletion difficult 

### Steps to Reproduce

1. Enter any number of grave accents in a text-input field with a text: ````´´´´´Testing 
2. double click the field to select everything 
3. delete the selected text 

#### Expected behavior
The grave accents should be shown as single letters and be deleted after everything is selected 

![Bildschirmfoto 2021-12-22 um 11 42 03](https://user-images.githubusercontent.com/91674611/147081156-bb35af8b-a4b1-4942-a476-484398f206c8.png)

#### Actual behavior
The grave accents are all in one place and cannot be deleted by selecting with a double click. 

![Bildschirmfoto 2021-12-22 um 11 41 43](https://user-images.githubusercontent.com/91674611/147080904-de25be1d-09b8-4592-844d-b474ae2ef6b7.png)

### Affected Versions

Neos: 7.3

UI: 7.3

**Comment by mhsdesign** [comment] 2021-12-23 19:39
Yes same issue here.
It is caused by the used font '**Noto Sans**'.

I tried this font out online with backticks but it will also not work: https://fonts.google.com/noto/specimen/Noto+Sans

The problem occurs not only in input fields, but wherever this font is used and where individual backticks/grave accents may appear.

I lately had a corrupted message in the Neos ui somewhere (i cant recall where excactly but i recreated it ^^)
![image](https://user-images.githubusercontent.com/85400359/147285048-4a8e64db-6a4b-4faa-92c2-abb3e5e15693.png)
expected:
This is just `` a demo with ```` some é funny ´´ backticks ```'

**Comment by mhsdesign** [comment] 2021-12-23 19:59
The font that the current Neos UI uses: https://github.com/neos/neos-ui-compiled/blob/master/Resources/Public/Styles/Font-61c3431e4e0ac62b136bc26b427ee05f.ttf is outdated. (Not updated in 3 Years) the command `fc-query Font-61c3431e4e0ac62b136bc26b427ee05f.ttf` says fontversion: 68157. (funny enough, it seems to be the same version as what the google servers are currently hosting (fonts.google....): https://github.com/googlefonts/noto-fonts/issues/736#issuecomment-768889258)

The latest Noto sans regular https://github.com/googlefonts/noto-fonts/blob/c8daccda0216efa71254f625e4ffaba2782c2090/hinted/ttf/NotoSans/NotoSans-Regular.ttf has the fontversion: 131531 (where this bug is fixed.)

So the fontfiles need to be updated - i have no idea (yet) how ^^

**Comment by mhsdesign** [comment] 2021-12-23 20:03
Its basically an issue since ... ever: https://github.com/neos/neos-ui/issues/2442

**Comment by mhsdesign** [comment] 2021-12-23 21:00
Okay the newer font files just need to be placed here: https://github.com/neos/neos-ui/tree/master/Resources/Public/Fonts

My question would be: since google doesnt serve the latest version - should we use the latest commit from main https://github.com/googlefonts/noto-fonts/tree/main or maybe a tagged 2020 version https://github.com/googlefonts/noto-fonts/tree/v20201206-phase3 will do too...

And should do we use hinted or unhinted fonts 😅?

**Comment by markusguenther** [comment] 2021-12-28 19:02
Thanks for reporting the issue and discussing :)
I have added a new version of the font, and now it is working.

Happy testing ;)

**Comment by markusguenther** [comment] 2022-01-03 11:32
Will be released with the next UI version (5.3.13 and newer)

**Closed** 2022-01-03 11:31 UTC
Labels: Bug, Good first issue, 5.3
