### ISSUE TITLE
Table settings are not usable

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#3360] opened 2023-02-13 14:50 UTC
### Description

When a table is inserted, the table settings are not usable. Also, the buttons are misaligned. Related to #3321

### Steps to Reproduce

1. Insert a table
2. Try to open a dropdown

#### Expected behavior

The dropdown opens and a can adjust the table

#### Actual behavior

![CleanShot 2023-02-13 at 15 48 41](https://user-images.githubusercontent.com/4510166/218490082-edf756f2-906e-40e2-a6e6-35b542000a33.gif)

The buttons are also always visible, even when no table is selected

### Affected Versions

Neos: 8.2.2

UI: 8.2.4

**Comment by markusguenther** [comment] 2023-02-13 15:36
<img width="1434" alt="Screenshot 2023-02-13 at 16 35 51" src="https://user-images.githubusercontent.com/1014126/218501989-194799e1-243f-4a1e-8b82-30afc6152a81.png">
Which browser? I use firefox and it works

**Comment by markusguenther** [comment] 2023-02-13 15:59
Tested now, Safari, Chrome, Firefox and Edge (chrome) in the latest versions... with the Demo it works. Could it be that custom styles conflict with the buttons?

**Comment by markusguenther** [comment] 2023-02-13 16:14
Like I mentioned in https://github.com/neos/neos-ui/issues/3361 maybe a difference between dev and production build.

**Comment by markusguenther** [comment] 2023-02-13 16:53
I tried the steps from the ui-minified script and that works. So, when I execute `make build-production` and copy the files from `Resources/Public/Build/` to the neos-ui-compiled the UI seems to run normal.

But currently I don't know what is the root cause.

**Comment by jonnitto** [comment] 2023-02-13 16:56
As fare as I see, there is some postcss nesting plugin missing
<img width="646" alt="CleanShot 2023-02-13 at 17 55 33@2x" src="https://user-images.githubusercontent.com/4510166/218521731-6ea17fcc-5fd5-4a47-8907-752355386c81.png">

**Comment by markusguenther** [comment] 2023-02-13 17:07
But as the make build-production works, it needs to be something different I guess...
But at the moment I don't know where it has been broken in the pipeline.

**Comment by markusguenther** [comment] 2023-02-13 18:33
Created `8.2.5-beta1` and no difference... so there has to be an issue in the pipeline for the minify part

**Comment by markusguenther** [comment] 2023-02-13 21:29
Has been resolved with version `8.2.6`

**Closed as completed by markusguenther** 2023-02-13 21:29 UTC
Labels: Bug, 8.2
