### ISSUE TITLE
Node Creation Dialog shows i18n as label for node-title

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-ui#1668] opened 2018-03-01 11:43 UTC
![image](https://user-images.githubusercontent.com/883552/36843027-e459ef64-1d4d-11e8-99d2-f0fd5041979e.png)

### Steps to Reproduce

1. Create a document node

#### Expected behavior

The creation dialog should display the correct label for the title-field

#### Actual behavior

"i18n" is shown as label.

### Affected Versions

Neos: 3.3.6
UI: 1.0.7

**Comment by dimaip** [comment] 2018-03-01 11:47
Duplicate of #1422

**Comment by dimaip** [comment] 2018-03-01 11:48
Btw, an easy first pick ;)

**Closed by dimaip** 2018-03-01 11:47 UTC

**Comment by DrillSergeant** [comment] 2018-03-01 12:00
Oh, did not see that issue when filtering issues for "dialog". :-)
